if [ -x /usr/sbin/squid ]; then
  SQUID=/usr/sbin/squid
else
  echo "No squid binary found"
  exit 1
fi

# ensure all cache dirs are there
install -d -o squid -g squid -m 750 /var/cache/squid-deb-proxy/
install -d -o squid -g squid -m 750 /var/log/squid-deb-proxy/
if [ ! -d /var/cache/squid-deb-proxy/00 ]; then
  $SQUID -z -N -f /etc/squid-deb-proxy/squid-deb-proxy.conf
fi

# generate pkg blacklist acl file
PKG_BLACKLIST_DIR=/etc/squid-deb-proxy/pkg-blacklist.d
PKG_BLACKLIST=/etc/squid-deb-proxy/autogenerated/pkg-blacklist-regexp.acl
/usr/share/squid-deb-proxy/concat-file-from-dir.sh "$PKG_BLACKLIST_DIR" "$PKG_BLACKLIST"
# postprocess for regexp format
sed -i -r '/^#/d;/^$/d;s#(.*)#\/\1_.*\.deb$#g' $PKG_BLACKLIST

# generate mirror file
MIRROR_DESTDOMAIN_DIR=/etc/squid-deb-proxy/mirror-dstdomain.acl.d
MIRROR_DESTDOMAIN=/etc/squid-deb-proxy/autogenerated/mirror-dstdomain.acl
/usr/share/squid-deb-proxy/concat-file-from-dir.sh "$MIRROR_DESTDOMAIN_DIR" "$MIRROR_DESTDOMAIN" "/etc/squid-deb-proxy/mirror-dstdomain.acl"

# generate the allowed-networks file
ALLOWED_NETWORKS_DIR=/etc/squid-deb-proxy/allowed-networks-src.acl.d
ALLOWED_NETWORKS=/etc/squid-deb-proxy/autogenerated/allowed-networks-src.acl
/usr/share/squid-deb-proxy/concat-file-from-dir.sh "$ALLOWED_NETWORKS_DIR" "$ALLOWED_NETWORKS" "/etc/squid-deb-proxy/allowed-networks-src.acl"

